# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('date_and_time', models.DateTimeField(verbose_name='Date and time')),
                ('price', models.CharField(default='Free', max_length=50)),
                ('email_subject', models.CharField(default='', help_text='The subject line for the e-mail sent out to guests.', max_length=255)),
                ('email_message', models.TextField(default='', help_text='The body of the e-mail sent out to guests.')),
            ],
            options={
                'ordering': ['date_and_time'],
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe'), ('no_rsvp', "Hasn't RSVPed yet")], default='no_rsvp', max_length=32)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('street_address', models.CharField(max_length=50, verbose_name='Street Address')),
                ('city', models.CharField(default='Montreal', max_length=20, verbose_name='City')),
                ('country', models.CharField(default='Canada', max_length=20, verbose_name='Country')),
                ('province', models.CharField(default='QC', max_length=2, verbose_name='Province')),
                ('postal_code', models.CharField(max_length=6, verbose_name='Postal Code')),
                ('lat', models.CharField(blank=True, max_length=50)),
                ('lng', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
            },
        ),
    ]
