# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
