# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_calendar', '0002_auto_20160830_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date_and_time'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ends',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starts',
        ),
        migrations.AddField(
            model_name='event',
            name='date_and_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Date and time'),
        ),
    ]
