# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_calendar', '0003_auto_20160922_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group of users you want to send the e-mail invite to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.Group'),
        ),
    ]
