# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 17:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_calendar', '0004_auto_20160831_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 31, 13, 34, 47, 157204), verbose_name='Date and time'),
        ),
    ]
