# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_calendar', '0005_auto_20160831_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='modified_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 1, 18, 25, 54, 821920), verbose_name='Date and time'),
        ),
    ]
