# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 22:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game_calendar', '0006_auto_20160901_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 1, 22, 30, 52, 193891, tzinfo=utc), verbose_name='Date and time'),
        ),
    ]
