# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_calendar', '0007_auto_20160901_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_and_time',
            field=models.DateTimeField(verbose_name='Date and time'),
        ),
    ]
