# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_calendar', '0008_auto_20160901_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='description',
        ),
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(default='Montreal', max_length=20, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='venue',
            name='country',
            field=models.CharField(default='Canada', max_length=20, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='venue',
            name='latlng',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='postal_code',
            field=models.CharField(default='H4X1K6', max_length=6, verbose_name='Postal Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='province',
            field=models.CharField(default='QC', max_length=2, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='venue',
            name='street_address',
            field=models.CharField(default='58 Ainslie Road', max_length=50, verbose_name='Street Address'),
            preserve_default=False,
        ),
    ]
