# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_calendar', '0009_auto_20160908_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='latlng',
        ),
        migrations.AddField(
            model_name='venue',
            name='lat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='venue',
            name='lng',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
