# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_calendar', '0010_auto_20160908_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('attending_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe'), ('no_rsvp', "Hasn't RSVPed yet")], default='no_rsvp', max_length=32)),
                ('number_of_guests', models.SmallIntegerField(default=0)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='email_message',
            field=models.TextField(default='', help_text='The body of the e-mail sent out to guests.'),
        ),
        migrations.AddField(
            model_name='event',
            name='email_subject',
            field=models.CharField(default='', help_text='The subject line for the e-mail sent out to guests.', max_length=255),
        ),
        migrations.AddField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='game_calendar.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together=set([('event', 'email')]),
        ),
    ]
